vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set number")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.g.mapleader = " "
vim.cmd("map <C-h> <C-w>h")
vim.cmd("map <C-j> <C-w>j")
vim.cmd("map <C-k> <C-w>k")
vim.cmd("map <C-l> <C-w>l")
vim.cmd("nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>")
vim.api.nvim_set_keymap('n', '<leader>of', '<cmd>lua vim.diagnostic.open_float()<CR>', { noremap = true, silent = true })
